env:
  TERM: xterm-256color

window:
  opacity: 1
  padding:
    x: 30
    y: 20

    dynamic_padding: false

font:
  normal:
    family: Space Mono NF
    style:  Regular

  bold:
    family: Space Mono NF
    style: Bold

  italic:
    family: Space Mono NF
    style: Italic

  bold_italic:
    family: Space Mono NF
  size: 11.0



live_config_reload: true

schemes:
  # Tokyo Night theme, based on both:
  #   https://github.com/ghifarit53/tokyonight-vim
  #   https://github.com/enkia/tokyo-night-vscode-theme
  tokyo-night: &tokyo-night
    # Default colors
    primary:
      background: '0x1a1b26'
      foreground: '0xa9b1d6'

    # Normal colors
    normal:
      black:   '0x32344a'
      red:     '0xf7768e'
      green:   '0x9ece6a'
      yellow:  '0xe0af68'
      blue:    '0x7aa2f7'
      magenta: '0xad8ee6'
      cyan:    '0x449dab'
      white:   '0x787c99'

    # Bright colors
    bright:
      black:   '0x444b6a'
      red:     '0xff7a93'
      green:   '0xb9f27c'
      yellow:  '0xff9e64'
      blue:    '0x7da6ff'
      magenta: '0xbb9af7'
      cyan:    '0x0db9d7'
      white:   '0xacb0d0'

  tokyo-night-storm: &tokyo-night-storm
    # Default colors
    primary:
      background: '0x24283b'
      foreground: '0xa9b1d6'

    # Normal colors
    normal:
      black:   '0x32344a'
      red:     '0xf7768e'
      green:   '0x9ece6a'
      yellow:  '0xe0af68'
      blue:    '0x7aa2f7'
      magenta: '0xad8ee6'
      cyan:    '0x449dab'
      white:   '0x9699a8'

    # Bright colors
    bright:
      black:   '0x444b6a'
      red:     '0xff7a93'
      green:   '0xb9f27c'
      yellow:  '0xff9e64'
      blue:    '0x7da6ff'
      magenta: '0xbb9af7'
      cyan:    '0x0db9d7'
      white:   '0xacb0d0'

  tokyo-night-storm: &gruvbox
    # Default colors
    primary:
      background: '0x282828'
      foreground: '0xdfbf8e'

    # Normal colors
    normal:
      black:   '0x665c54'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xe78a4e'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xdfbf8e'

    # Bright colors
    bright:
      black:   '0x928374'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xe3a84e'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xdfbf8e'

colors: *gruvbox

key_bindings: 

  - { key: Key0, mods: Control, action: ResetFontSize }

  - { key: Equals, mods: Control, action: IncreaseFontSize }

  - { key: Minus, mods: Control, action: DecreaseFontSize }
