#!/bin/sh

# Autostart

# emacs daemon
/usr/bin/emacs --daemon & 

## Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

## Autokill
killall -9 ksuperkey xfce4-power-manager &
killall sxhkd; sxhkd &
killall dunst; dunst &

## Power Manager
xfce4-power-manager &

## Compositor
picom -b &

## Background
nitrogen --restore &

## Redshift (Optional)
# redshift -x && redshift -O 4000k &

## Fix Cursor
xsetroot -cursor_name left_ptr &

## Bar
$HOME/.config/polybar/launch.sh &

## Super Key
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Variable

alias bc='bspc config'
alias br='bspc rule'

# Workspaces

bspc monitor -d 1 2 3 4 5 6

# Config

bc border_width 0
bc window_gap 10
bc border_radius 15
bc split_ratio 0.50
bc bottom_padding 0
bc focused_border_color "#f7768e"
bc normal_border_color "#353b45"


bc borderless_monocle true
bc gapless_monocle false
bc focus_follows_pointer true
bc paddingless_monocle true
bc single_monocle false

# Rules

br -a feh state=floating
br -a sxiv state=floating
br -a mpv state=floating
br -a Conky state=floating
br -a stalonetray state=floating
br -a Lxappearance state=floating
br -a KeePassXC state=floating 
br -a Emacs state=tiled desktop='^4' follow=on focus=on
br -a Discord desktop='^5' follow=on focus=on
br -a Zathura state=tiled follow=on focus=on
br -a Pavucontrol state=floating
